### ISSUE TITLE
error  No current entries

### ISSUE THREAD

**Issue by eArabic** [phhpro/easy-journal#1]
Hello dear friend
I drew this script, but unfortunately did not work for me, did not show anything, I did not know how to do, thank you very much.
This is the error message: No current entries.

**Comment by phhpro** [comment]
Huh? "No current entries" simply means there are no entries yet. Somewhat logical and certainly not an error :) Since I know your path is broken, make sure to patch line #44 first before going any further. Once you have the proper path in place, call the script with the editor token. Default is ?edit -- see line #56 and change to your likes. You should now have a simple editor window to add, modify, or delete entries. Quit the editor when done, and voila...
